### ISSUE TITLE
Can't get friends.js from outside of src

### ISSUE THREAD

**Issue by asBrettisay** [DevMountain/react-friends#3]
CRA only supports babelizing from inside of src.

**Comment by r-walsh** [comment]
@asBrettisay Really? I'm not very familiar with CRA, but they're using Webpack so it shouldn't matter where the file came from. Is it a config thing or a convention thing?

**Comment by asBrettisay** [comment]
@r-walsh  [Check out this issue from CRA](https://github.com/facebookincubator/create-react-app/issues/834)

**Comment by r-walsh** [comment]
Weird, at least it's an easy fix on our end.

**Comment by asBrettisay** [comment]
I would have fixed it without making an issue, but I was in class and I didn't want to forget

**Comment by asBrettisay** [comment]
Fixed by #5
